### ISSUE TITLE
Problem appeared again: Video returned by YouTube isn't what was requested

### ISSUE THREAD

**Issue by Arskamann** [lavalink-devs/lavaplayer#97]
So this had already been fixed in 727959e9f621fc457b3a5adafcfffb55fdeaa538-SNAPSHOT

but it appeared again, any solutions? All youtube tracks fail.

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Video returned by YouTube isn't what was requested
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:59)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:230)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:254)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:250)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:103)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:68)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:46)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:218)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:149)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:412)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:394)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:156)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$loadItem$0(DefaultAudioPlayerManager.java:175)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: {"responseContext":{"serviceTrackingParams":[{"service":"GFEEDBACK","params":[{"key":"ipcc","value":"0"},{"key":"is_viewed_live","value":"False"},{"key":"is_alc_surface","value":"false"},{"key":"logged_in","value":"0"},{"key":"e","value":"23858058,23888717,23946420,23966208,23983296,23998056,24004644,24036947,24077241,24078649,24080738,24117491,24120820,24135310,24135943,24143331,24166867,24181174,24187377,24230811,24232551,24241378,24265964,24267186,24290971,24299875,24377598,2439798

**Comment by devoxin** [comment]
Are you using IP rotation?

**Comment by Arskamann** [comment]
> Are you using IP rotation?

How can I do that?

**Comment by Arskamann** [comment]
> Are you using IP rotation?

Nice, I switched my bot to another ip and it works. Youtube has blocked my main IP :DDD

**Comment by mrhalleg** [comment]
I have the same problem. Im getting this error on the server as well as on my development-machine. i have tried using a vpn on my development machine (proton-vpn), still does not work.

**Comment by duncte123** [comment]
> I have the same problem. Im getting this error on the server as well as on my development-machine. i have tried using a vpn on my development machine (proton-vpn), still does not work.

Join the lavalink discord server, we have patch that you can include

**Comment by mrhalleg** [comment]
yep that works, thanks!

**Comment by DisruptionSystemsINC** [comment]
> > I have the same problem. Im getting this error on the server as well as on my development-machine. i have tried using a vpn on my development machine (proton-vpn), still does not work.
> 
> Join the lavalink discord server, we have patch that you can include

Will there be a fix merged into the maven repo?

**Comment by devoxin** [comment]
No. The built-in youtube source will be getting deprecated and phased out in favour of https://github.com/lavalink-devs/youtube-source.

**Comment by Arskamann** [comment]
> > I have the same problem. Im getting this error on the server as well as on my development-machine. i have tried using a vpn on my development machine (proton-vpn), still does not work.
> 
> Join the lavalink discord server, we have patch that you can include

I checked the discord but all that I can find is people talking about ip rotation. Is there a fix that I can include to my maven pom file direcly?

**Comment by devoxin** [comment]
Users still experiencing this issue after upgrading to the new Lavaplayer jar or to [youtube-source](https://github.com/lavalink-devs/youtube-source) are advised to enable IP rotation as this issue stems from being detected as bot, and blocked.

If you continue to encounter this problem even with IP rotation, please track this under issue #90.

Closing due to duplication/issue consolidation.
